platforms:
  android:
    versionName: 1.0.0
    manifest:
      - file: AndroidManifest.xml
        target: manifest
        merge: |
          <manifest>
            <uses-permission android:name="android.permission.CAMERA" />
            <uses-permission android:name="android.permission.RECORD_AUDIO" />
            <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
          </manifest>
      - file: AndroidManifest.xml
        target: manifest/application/activity
        attrs:
          android:exported: true
          android:networkSecurityConfig: "@xml/network_security_config"
    res:
      - path: xml
        file: network_security_config.xml
        text: |
          <?xml version="1.0" encoding="utf-8"?>
          <network-security-config>
            <base-config>
              <trust-anchors>
                <certificates src="system"/>
                <certificates src="user"/>
              </trust-anchors>
            </base-config>
          </network-security-config>
  ios:
    version: 1.0.0
